services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  odoo:
    image: odoo
    container_name: odoo
    depends_on:
      - db
    ports:
      - "80:8069"
    environment:
      HOST: ${POSTGRES_HOST}
    volumes:
      - ./etc/odoo.conf:/etc/odoo.conf
      - ./odoo_data:/var/lib/odoo
