services:
  odoo:
    image: odoo-opam:18
    container_name: odoo
    user: "2000:2000"
    depends_on:
      - postgres
    ports:
      - "80:8069"
    environment:
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      HOST: ${POSTGRES_HOST}
    volumes:
      - /home/odoo/data:/var/lib/odoo
      - /home/odoo/extra-addons:/mnt/extra-addons
  postgres:
    image: postgres-opam:17.2
    container_name: postgres
    user: "2001:2001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - /home/postgres/data:/var/lib/postgresql/data