#!/bin/bash

# Verifica si el usuario es root (ID de usuario 0)
if [ "$(id -u)" -ne 0 ]; then
    echo "Este script debe ejecutarse como root."
    exit 1
fi

# Ruta a los módulos
MODULES_DIR="./vendor/INSTALL"

# Incluir el módulo de comprobaciones siempre antes de ejecutar los otros scripts
source "${MODULES_DIR}/validate"

# Comprobar que se cumplen las condiciones básicas
validate

case "$1" in
  files)
    source "${MODULES_DIR}/files"
    configure_folders
    ;;
  images)
    source "${MODULES_DIR}/images"
    configure_images
    ;;
  db)
    source "${MODULES_DIR}/db"
    configure_db
    ;;
  service)
    source "${MODULES_DIR}/service"
    configure_service
    ;;
  *)
    echo "Uso: ./install.sh {files|images|db|service}"
    ;;
esac
